# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ComponentValidator < Formula
  desc "Utility to validate a component structure"
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/garethjevans/component-validator/releases/download/0.1.0/component-validator-darwin-arm64.tar.gz"
      sha256 "9b2fe7bc35b35f61dfa5cd34370c0def83b1d59ad3d0db8ea1369064a2fc6afd"

      def install
        bin.install "component-validator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/garethjevans/component-validator/releases/download/0.1.0/component-validator-darwin-amd64.tar.gz"
      sha256 "b2948735742cb5e3466b911d40cf9aa55435fa7b84c3e68051a7d7b45f8abc61"

      def install
        bin.install "component-validator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/garethjevans/component-validator/releases/download/0.1.0/component-validator-linux-arm64.tar.gz"
      sha256 "87a9c8ba3f9d9f20fca707889316fe38bf3daf6d897a632d12915931adca4bda"

      def install
        bin.install "component-validator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/garethjevans/component-validator/releases/download/0.1.0/component-validator-linux-amd64.tar.gz"
      sha256 "16278df9e93a32955d525d845b521e8673cf5e8522e018b1b68605ef80fa8d1a"

      def install
        bin.install "component-validator"
      end
    end
  end
end
