# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inspect < Formula
  desc "Utility to inspect docker containers"
  homepage ""
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/garethjevans/inspect/releases/download/0.0.3/inspect-darwin-amd64.tar.gz"
    sha256 "4b28a0397486a751e0fea6b28c540c94524d47a4a293c7189f57dc2dc1cf614f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/garethjevans/inspect/releases/download/0.0.3/inspect-linux-amd64.tar.gz"
    sha256 "02c0ced3f143963aa050e0be21c4e7f7c20771da37dce6491466dd0477d0723b"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/garethjevans/inspect/releases/download/0.0.3/inspect-linux-arm64.tar.gz"
    sha256 "51de3170cd7033c07afc64e08f0e953f386d7a5c912abffccc36b722ab2f8212"
  end

  def install
    bin.install "inspect"
  end
end
