# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inspect < Formula
  desc "Utility to inspect docker containers"
  homepage ""
  version "0.0.10"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/garethjevans/inspect/releases/download/0.0.10/inspect-darwin-amd64.tar.gz"
    sha256 "715fda52864be5ca384f5ca5690111812cee5faea25bd1676b8b2e3675fc7175"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/garethjevans/inspect/releases/download/0.0.10/inspect-darwin-arm64.tar.gz"
    sha256 "7f71ac323a1f15a8677afd1f8a1016d6374e03a212aeadb92beee10a58b0ca13"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/garethjevans/inspect/releases/download/0.0.10/inspect-linux-amd64.tar.gz"
    sha256 "015f0f6d69743a53b5ef5fbfc8f46d9737ebd234237e78761e7daff6b011cc2b"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/garethjevans/inspect/releases/download/0.0.10/inspect-linux-arm64.tar.gz"
    sha256 "87df5f804862ef1cecfa0760414a32fee990c37778ffcc5222a44a254706af54"
  end

  def install
    bin.install "inspect"
  end
end
