# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inspect < Formula
  desc "Utility to inspect docker containers"
  homepage ""
  version "0.0.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/garethjevans/inspect/releases/download/0.0.7/inspect-darwin-amd64.tar.gz"
    sha256 "2bc1a4cac67456859c066b3332338d1b153e990f8643005d306b142b5feb16e2"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/garethjevans/inspect/releases/download/0.0.7/inspect-linux-amd64.tar.gz"
    sha256 "3a34eec9ed7c165087b25439e7564418716f0718c2b2d77c175c775fdf03178f"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/garethjevans/inspect/releases/download/0.0.7/inspect-linux-arm64.tar.gz"
    sha256 "28c9cabfe5b83f5faffbbdc1df7c1237f169a33278fbeb9984d3afb5eff2c947"
  end

  def install
    bin.install "inspect"
  end
end
