# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scm < Formula
  desc "Utility to validate a component structure"
  homepage ""
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/garethjevans/scm/releases/download/0.3.0/scm-darwin-amd64.tar.gz"
      sha256 "abb74d0fbf193129fd7dc85362b50362a52f37126815ad598dc5fed9ca6f1773"

      def install
        bin.install "scm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/garethjevans/scm/releases/download/0.3.0/scm-darwin-arm64.tar.gz"
      sha256 "7afd264ba6c8c2cf6c638e06cabf68c26ceea92abc3e4ed45b31a84a16978d16"

      def install
        bin.install "scm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/garethjevans/scm/releases/download/0.3.0/scm-linux-arm64.tar.gz"
      sha256 "16512adcc0bb58a0ad9dbb7dc13736f9c3ef5ced27fdc53de2cd3103b6e9750c"

      def install
        bin.install "scm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/garethjevans/scm/releases/download/0.3.0/scm-linux-amd64.tar.gz"
      sha256 "440cc34699229a8b807b972c7de5f58500e0934656e6fd6ece0dbacdb53845e3"

      def install
        bin.install "scm"
      end
    end
  end
end
