# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scm < Formula
  desc "Utility to validate a component structure"
  homepage ""
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/garethjevans/scm/releases/download/0.3.1/scm-darwin-amd64.tar.gz"
      sha256 "d55cdcf0cc6ac412993574913aff9ce6e2e2011d4f7d593420ec20724a59b138"

      def install
        bin.install "scm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/garethjevans/scm/releases/download/0.3.1/scm-darwin-arm64.tar.gz"
      sha256 "7d469e9b092376bfc805ea8131a7b6bda5d140b3c0c4ab37a7f3ba8c2aa26a00"

      def install
        bin.install "scm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/garethjevans/scm/releases/download/0.3.1/scm-linux-amd64.tar.gz"
      sha256 "b13c0b08710f3974f11747fbd1fa6ac26a7bb06982abf5e3c82b7dd99f0884ea"

      def install
        bin.install "scm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/garethjevans/scm/releases/download/0.3.1/scm-linux-arm64.tar.gz"
      sha256 "a7e21a1d401c3e5b136f9a3b06a14913bda3abb9ee8e146fc7e023d9bdaae6be"

      def install
        bin.install "scm"
      end
    end
  end
end
