# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scm < Formula
  desc "Utility to validate a component structure"
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/garethjevans/scm/releases/download/0.1.0/scm-darwin-arm64.tar.gz"
      sha256 "3750f06c68069ecef991445af249b74fcf6832a935de23a09be29f726782e728"

      def install
        bin.install "scm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/garethjevans/scm/releases/download/0.1.0/scm-darwin-amd64.tar.gz"
      sha256 "3ddd57204dfb22f67b2ea9cece4fb82736c6a839baf9a0a585aa126e305867a8"

      def install
        bin.install "scm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/garethjevans/scm/releases/download/0.1.0/scm-linux-amd64.tar.gz"
      sha256 "c3287e97da1226210cf902022955945d73f0dc4ca76bb284ccb16b32a17cf31b"

      def install
        bin.install "scm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/garethjevans/scm/releases/download/0.1.0/scm-linux-arm64.tar.gz"
      sha256 "57a2bdcc83cf8cf894703c21f85a00b80faf2ececdf4a29d0f1f058f496632b1"

      def install
        bin.install "scm"
      end
    end
  end
end
