# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Semver < Formula
  desc "Utility to validate a component structure"
  homepage ""
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/garethjevans/semver/releases/download/0.1.3/semver-darwin-amd64.tar.gz"
      sha256 "b9b4b6dec08a5d0a98707bfcf352ec0f19f6ba7ab6b666b676ab19ed8d63d9e6"

      def install
        bin.install "semver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/garethjevans/semver/releases/download/0.1.3/semver-darwin-arm64.tar.gz"
      sha256 "1bae8f07263b54c03ecd67901d8dfab423cca1965e7ca47ca30fb5a648c69065"

      def install
        bin.install "semver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/garethjevans/semver/releases/download/0.1.3/semver-linux-amd64.tar.gz"
      sha256 "1ade436d6ad7080750cc94d7064148400c7cd195e5643b1f2387a8ff7f89c58f"

      def install
        bin.install "semver"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/garethjevans/semver/releases/download/0.1.3/semver-linux-arm64.tar.gz"
      sha256 "493d43248ff9950c939184c32613ca668cdb168c249898ee284d112b6d2faced"

      def install
        bin.install "semver"
      end
    end
  end
end
