# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uc < Formula
  desc "Utility to update jenkins plugin.txt"
  homepage ""
  version "0.1.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/garethjevans/uc/releases/download/0.1.0/uc-darwin-amd64.tar.gz"
    sha256 "e0a46f50d364e651903663216ab52d6f2e625be2b5ba74ffd57a7af08a16c643"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/garethjevans/uc/releases/download/0.1.0/uc-darwin-arm64.tar.gz"
    sha256 "e7d151ddc1830c61fb72cf7eb054fbe4b98209df7acbd9a97fa3b45713b6572c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/garethjevans/uc/releases/download/0.1.0/uc-linux-amd64.tar.gz"
    sha256 "6cf5f670a595e9edbba3343968d20c62ff44fb0e52f13ab2afa5b7a92141817e"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/garethjevans/uc/releases/download/0.1.0/uc-linux-arm64.tar.gz"
    sha256 "9665240d21e49328772440bcd5b62b822305186b33e284c593e9b7e43d992f6f"
  end

  def install
    bin.install "uc"
  end
end
