# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uc < Formula
  desc "Utility to update jenkins plugin.txt"
  homepage ""
  version "0.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/garethjevans/uc/releases/download/0.0.5/uc-darwin-amd64.tar.gz"
    sha256 "9cd1a35e152ad5e04c0e02f6e9bbd9f4ee6664dc4a479e3480ceb773290e10ae"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/garethjevans/uc/releases/download/0.0.5/uc-linux-amd64.tar.gz"
    sha256 "f819a09b3f990ec3f859ee0470e245d419af208bc663102d8ef35cd6c51ad2ab"
  end

  def install
    bin.install "uc"
  end
end
