# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uc < Formula
  desc "Utility to update jenkins plugin.txt"
  homepage ""
  version "0.0.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/garethjevans/uc/releases/download/0.0.7/uc-darwin-amd64.tar.gz"
    sha256 "174fe1d2d7c6861563d7600084464c3bf4bee60de3e79f451aee5ebea007b8dc"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/garethjevans/uc/releases/download/0.0.7/uc-linux-amd64.tar.gz"
    sha256 "107b7b2add3b6ead13a2a3ecd27733ad2ae8c5193dca4f698a7322d4eaf361a7"
  end

  def install
    bin.install "uc"
  end
end
